const StudentsData = [
  {
    name:"Aayush Chand Thakuri",
    rollno: 1,
    address:"Bhansi",
    imgSrc:"./src/assets/sakshi.png",
  },
  {
    name:"Alisha Joshi",
    rollno: 2,
    address:"mahakali",
    imgSrc:"./src/assets/sakshi.png",
  },
  {
    name:"Sameer Dangaura",
    rollno: 30,
    address:"IDK",
    imgSrc:"./src/assets/sakshi.png",
  },
  {
    name:"Urmila Thalal",
    rollno: 37,
    address:"School Nera",
    imgSrc:"./src/assets/sakshi.png",
  },
  { name: "Sakshi Khatiwada", 
    rollno: 29, 
    address: "Bankhet",
    imgSrc: "./src/assets/sakshi.png"
  },
  {
    name: "Shekhar Singh Rawal",
    rollno: 32,
    address: "Bhashi",
    imgSrc:"./src/assets/shekhar.jpeg",
  },
  {
    name: "Yojana Pandey",
    rollno: 38,
    address: "Bhashi",
    imgSrc:"./src/assets/yojana.jpg",
  },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
  // {
  //   name: "Yojana Pandey",
  //   rollno: 38,
  //   address: "Bhashi",
  //   imgSrc:"./src/assets/yojana.jpg",
  // },
];

export default StudentsData;
